version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aroma-server
    restart: unless-stopped
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    env_file:
      - .env
    environment:
      - SERVER_HOST=0.0.0.0
      - POSTGRES_DSN=${POSTGRES_DSN}

      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET:-aroma-hub}
      - MINIO_USE_SSL=${MINIO_USE_SSL:-false}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - aroma-hub-network
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  postgres:
    image: postgres:17.4-alpine
    container_name: aroma-hub-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - aroma-hub-network
    deploy:
      resources:
        limits:
          memory: 1G
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  minio:
    image: minio/minio:latest
    container_name: aroma-hub-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s
    ports:
      - '${MINIO_API_PORT:-9000}:9000'
      - '${MINIO_CONSOLE_PORT:-9001}:9001'
    networks:
      - aroma-hub-network
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  aroma-hub-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local
